name: cashier_admin_keygen
description: 'Offline Ed25519 license key generator for Cashier POS'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^6.0.2
  ed25519_edwards: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
